## Quiz 5

Calculate covariance

In [1]:
sigmaA = 0.15; sigmaB = 0.3; correlation = 0.25;
sigmaAB = correlation*sigmaA*sigmaB;
print(sigmaAB)

0.01125


Calculate minimum standard deviation

In [2]:
alpha = (sigmaB**2-sigmaAB)/(sigmaA**2+sigmaB**2-2*sigmaAB);
print(alpha)
print(1-alpha)

0.875
0.125


Calculate total return

In [4]:
r1 = 0.1 ; r2 = 0.18; w1 = 0.5; w2 = 0.5;
r = r1*w1+r2*w2;
print(r)

0.14


Calculate porfolio standard deviation

In [5]:
import math
sigma = (sigmaA**2 * w1**2) + (sigmaB**2 * w2**2) + 2*w1*w2*sigmaAB;
print(math.sqrt(sigma))

0.18371173070873834


## Quiz 6

Two risky assets with expected rates of return 𝑟¯1=0.10 and 𝑟¯2=0.08 have identical variances and a known correlation coefficient 𝜌=0.50.  There is also a risk-free asset with a rate of return 𝑟𝑓=0.05.

Using mean-variance portfolio theory, find the optimal weight of asset 2.

In [6]:
r1 = 0.1; r2 = 0.08; p = 0.5; rf = 0.05;
s1 = r1-rf; s2= r2-rf;
w1 = (s1-p*s2)/((1-p)*(s1+s2));
w2 = (s2-p*s1)/((1-p)*(s1+s2));
print(w1, w2)

0.8750000000000001 0.12499999999999993


Two risky assets with expected rates of return 𝑟¯1=0.10 and 𝑟¯2=0.08 have identical variances and a known correlation coefficient 𝜌=0.99.  There is also a risk-free asset with a rate of return 𝑟𝑓=0.05.

Using mean-variance portfolio theory, find the optimal weight of asset 2.

Please round your numerical answer to three decimal places.

In [7]:
r1 = 0.1; r2 = 0.08; p = 0.99; rf = 0.05;
s1 = r1-rf; s2= r2-rf;
w1 = (s1-p*s2)/((1-p)*(s1+s2));
w2 = (s2-p*s1)/((1-p)*(s1+s2));
print(w1, w2)

25.374999999999986 -24.374999999999982


Question 3 : uncorrated assets with a desired mean return

Suppose there are three uncorrelated risky assets.  Each risky asset has variance equal to 1, and the mean return values for assets 1, 2, and 3 are:

𝑟¯1=0.10
𝑟¯2=0.20
𝑟¯3=0.30
Assume there is no risk-free asset available. 

By formulating and solving the equations for the efficient set, determine the value of the mean-variance optimal portfolio weight 𝑤1for asset 1, corresponding to the portfolio with a desired mean return of 𝑟¯=0.20.

Please round your numerical answer to two decimal places.

In [3]:
import numpy as np
r = 0.2;
B = np.array([[0,0,0,r,1]]);
V = np.array([[1,0,0,-1,-1],
              [0,1,0,-2,-1],
              [0,0,1,-3,-1],
              [0.1,0.2,0.3,0,0], #mean return value of each asset
              [1,1,1,0,0]]);
x = np.linalg.inv(V).dot(np.transpose(B))
print(x[0])

[0.33333333]


Question 4: uncorrelated assets with rf

Suppose there are three uncorrelated risky assets.  Each risky asset has variance equal to 1, and the mean return values for assets 1, 2, and 3 are:

𝑟¯1=0.10
𝑟¯2=0.20
𝑟¯3=0.30
Now assume there is a risk-free asset with rate 𝑟𝑓=0.05.

The one-fund theorem states that there is a single fund F of risky assets such that any efficient portfolio can be constructed as a combination of the fund F and the risk-free asset.  

What is the weight 𝑤1of asset 1 corresponding to the single fund F?

Please round your numerical answer to two decimal places.

In [10]:
rf = 0.05;
r_bar = np.array([0.1-rf,0.2-rf,0.3-rf]);
V = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]]);
x = np.linalg.inv(V).dot(np.transpose(r_bar))
w = np.zeros(shape=(3,1));
for i in range (0,3):
    w[i] = x[i]/np.sum(x);
print(x)
print(w)

[0.05 0.15 0.25]
[[0.11111111]
 [0.33333333]
 [0.55555556]]


Question 5

The information concerning the 1-year covariances and mean values of the rates of return on five risky securities (assets) is shown in the table below.

Screen Shot 2020-11-02 at 10.21.00 PM.png

The mean values in the column labeled 𝐫¯ are expressed on a percentage basis, whereas the covariances are expressed in units of (percent)2 / 100. For example, the first security has an expected rate of return of 15.1%, or 0.151, and a variance of return of 0.023.  And the covariance between security 1 and security 2 is 0.0093, while the covariance between security 1 and security 3 is 0.0062. 

Assume there is also a risk-free asset with 𝑟𝑓=10%.

The one-fund theorem states that there is a single fund F of risky assets such that any efficient portfolio can be constructed as a combination of the fund F and the risk-free asset.  

What is the weight 𝑤4 security 4 corresponding to the single fund F?

Please round your numerical answer to two decimal places.

In [11]:
import numpy as np
A = np.array([[1,0.5],[0.5,1]]);
B = np.array([[0.05,0.03]]);
x = np.linalg.inv(A).dot(np.transpose(B))
print(x)

[[0.04666667]
 [0.00666667]]


In [12]:
import numpy as np 
V = np.array([[2.3,0.93,0.62,0.74,-0.23],
              [0.93,1.4,0.22,0.56,0.26],
              [0.62,0.22,1.8,0.78,-0.27],
              [0.74,0.56,0.78,3.4,-0.56],
              [-0.23,0.26,-0.27,-0.56,2.6]]);
B = np.ones(shape=(5,1))
r_bar = np.array([[0.151,0.125,0.147,0.0902,0.1768]]);
v_a = np.linalg.inv(V).dot(B)
w_a = np.zeros(shape=(5,1));
for i in range (0,5):
    w_a[i] = v_a[i]/np.sum(v_a);
print(w_a)

[[0.08825144]
 [0.25086041]
 [0.28238423]
 [0.10375097]
 [0.27475295]]


In [13]:
r_bar_transpose = np.transpose(r_bar)
v_b = np.linalg.inv(V).dot(r_bar_transpose);
w_b = np.zeros(shape=(5,1));
for i in range (0,5):
    w_b[i] = v_b[i]/np.sum(v_b);
print(w_b)


[[0.15834987]
 [0.15535016]
 [0.31426329]
 [0.0379156 ]
 [0.33412109]]


In [14]:
r_f = 0.1
v_c = np.zeros(shape=(5,1));
for i in range (0,5):
    v_c[i] = v_b[i] - v_a[i]*r_f;
w_c = np.zeros(shape=(5,1));
for i in range(0,5):
    w_c[i] = v_c[i]/np.sum(v_c)
print(w_c)


[[ 0.31719998]
 [-0.06108573]
 [ 0.38650446]
 [-0.11127402]
 [ 0.46865531]]


Question 6

What is the portfolio variance of the single fund F in Question 5?

Please express your answer in decimal form, and round your numerical answer to four  decimal places.

In [15]:
C = np.matmul(np.transpose(w_c),V);
sigma = np.matmul(C,w_c)
print(sigma/100)

[[0.00989892]]


### Quiz 7 

In this problem there are only only two risky stocks, A and B, whose details are listed the table below.
 

Screen Shot 2020-11-03 at 6.27.04 PM.png

Furthermore, the correlation coefficient between the returns of stocks A and B is .  There is also a risk-free asset, and the market follows the CAPM exactly.

What is the expected rate of return on the market portfolio?

What is the standard deviation of  the market portfolio?

What is the beta of stock A?

What is the annual risk-free rate?



In [5]:
import math
nA = 100; nB = 150; 
pA = 1.50; pB = 2.00; 
rA = 0.15; rB = 0.12; 
sigmaA = 0.15; sigmaB = 0.09;
rho_AB=1/3;
rM = (nA*pA*rA + nB*pB*rB)/(nA*pA + nB*pB);
wA = (nA*pA)/(nA*pA + nB*pB);
wB = (nB*pB)/(nA*pA + nB*pB);
sigmaM = math.sqrt(wA**2 * sigmaA**2 + wB**2 * sigmaB**2 + 
                   2*rho_AB*wA*wB*sigmaA*sigmaB);
sigmaAM = wA*sigmaA**2 + rho_AB*wB*sigmaA*sigmaB;
beta_A = sigmaAM/(sigmaM**2);
rF = (rA - beta_A*rM)/(1-beta_A);
print(rM)
print(sigmaM)
print(beta_A)
print(rF)

0.13
0.09
1.2962962962962963
0.0625


Suppose there are only two risky assets in the market with expected rates of return, variances, and covariance as follows: 

𝑟¯1=0.10
𝑟¯2=0.20
 

𝜎21=0.04
𝜎22=0.09
 

𝜎1,2=0.03
The current annual risk-free rate 𝑟𝑓=0.05.

Find the weights 𝑤1 and 𝑤2 for the one fund F for this market, assuming market equilibrium and the CAPM holds.

In [7]:
import numpy as np
r1 = 0.1; r2 = 0.2; rf = 0.05; 
sigma1 = 0.04; sigma2 = 0.09; sigma12 = 0.03;
A = np.array([[sigma1, sigma12],[sigma12,sigma2]]);
B = np.array([[r1 - rf, r2 - rf]]);
v = np.linalg.inv(A).dot(np.transpose(B))
w = np.zeros(shape=(2,1));
for i in range (0,2):
    w[i] = v[i]/np.sum(v);
print(w)

[[0.]
 [1.]]


CAPM formula


In [9]:
rf = 0.1; sigmaA = 0.04; sigmaB = 0.02; sigmaAB = 0.01; rM = 0.18;
sigmaM = (sigmaA + 2*sigmaAB + sigmaB)*1/4
betaA = ((sigmaA+sigmaAB)/sigmaM)*1/2
betaB = ((sigmaB+sigmaAB)/sigmaM)*1/2
rA = rf + betaA*(rM - rf)
rB = rf + betaB*(rM-rf)
print(rA)
print(rB)

0.19999999999999998
0.16


## Quiz 8

For a portfolio of 500 risky assets, the mean-variance portfolio optimization approach requires the estimation of how many parameters?

In [10]:
a = 500;
print(a+a+a*(a-1)/2)

125750.0


Let the risk-free rate rf = 8%.

Suppose that the rate of return of the market portfolio has an expected value of 12% and a standard deviation of 15%.  

Now consider a risky asset that has a covariance of 0.09 with the market. According to the Capital Asset Pricing Model (CAPM), what is the expected rate of return of this asset?

Please express your numerical answer as a percentage (not decimal) and round your answer to the nearest integer.

In [16]:
rf = 0.08; rM = 0.12; sigmaM = 0.15; sigmaiM = 0.09;
betaA = sigmaiM/(sigmaM**2)
rA = rf + betaA*(rM - rf)
print(rA)

0.24



Berkshire Hathaway (ticker:  BRK/A) is an American multinational conglomerate holding company headquartered in Omaha, Nebraska.  The company is known for its control and leadership by Warren Buffett.  

The data in the table above show the annual rate of return, in percentage, for BRK/A and the S&P 500 index with dividends included for the 10 year period spanning 2010 to 2019. The risk-free rate is zero.

Note that the numbers in parenthesis denote negative rates of return, and BRK/A does not pay a dividend.

You are asked to model the annual returns for BRK/A using a one-factor model, with the S&P 500 index annual returns with dividends included as the one factor as follows:


Find the optimal values for  and , using all the data in the table, such that the total squared error is minimized, where the total squared error is equal to


What is the value of ?  Please round your numerical answer to four decimal places.



In [17]:
import numpy as np
from statistics import variance
stock_1 = np.array([21.4, -4.7, 16.8, 32.7, 27.0, -12.5, 23.4, 21.9, 2.8, 11.0]);
market = np.array([15.1, 2.1, 16.0, 32.4, 13.7, 1.4, 12.0, 21.8, -4.4, 31.5]);
rf = 0;
var_market = variance(market)
var_stock1 = variance(stock_1)
mu_market = np.mean(market)
mu_stock1 = np.mean(stock_1)

In [18]:
B1 = np.cov(stock_1,market);
beta1 = B1[1,0]/var_market
alpha1 = (mu_stock1-rf)- beta1*(mu_market-rf)
e_stock1 = stock_1 - alpha1 - beta1*market
e_var1 = var_stock1 - (beta1**2)*var_market
print(beta1)
print(B1)

0.8176435996997687
[[213.15955556 122.97577778]
 [122.97577778 150.40266667]]
