There are just three assets with rates of return r1,r2, and r3, respectively.
The covariance matrix and the expected rates of return are: 

(a) Find the minimum-variance portfolio.
(b) Find another efficient portfolio by setting λ = 1, µ = 0.
(c) If the risk-free rate is rf = .2, find the efficient portfolio of risky assets.

In [41]:
import numpy as np 
V = np.array([[2,1,0],[1,2,1],[0,1,2]]);
B = np.ones(shape=(3,1))
r_bar = np.array([[4,8,8]]);
v_a = np.linalg.inv(V).dot(B)
w_a = np.zeros(shape=(3,1));
for i in range (0,3):
    w_a[i] = v_a[i]/np.sum(v_a);
print(w_a)

[[0.5]
 [0. ]
 [0.5]]


In [43]:
r_bar_transpose = np.transpose(r_bar)
v_b = np.linalg.inv(V).dot(r_bar_transpose);
w_b = np.zeros(shape=(3,1));
for i in range (0,3):
    w_b[i] = v_b[i]/np.sum(v_b);
print(w_b)

[[0.16666667]
 [0.33333333]
 [0.5       ]]


In [31]:
r_f = 0.2
v_c = np.zeros(shape=(3,1));
for i in range (0,3):
    v_c[i] = v_b[i] - v_a[i]*r_f;
w_c = np.zeros(shape=(3,1));
for i in range(0,3):
    w_c[i] = v_c[i]/np.sum(v_c)
print(w_c)

[[0.15517241]
 [0.34482759]
 [0.5       ]]
