### 4.3 Construction of a zero

In [6]:
import numpy as np
A = np.array([[100,100],[9,7]]);
B = np.array([100,0]);
X = np.linalg.inv(A).dot(B) #solve system equation 
print(X)
print(B)

[-3.5  4.5]
[100   0]


In [5]:
price = -3.5*101.00+4.5*93.20;
print(price)

65.90000000000003


### 4.7 Bond taxes

In [6]:
A = np.array([[100,100],[10,7]]);
B = np.array([100,0]);
X = np.linalg.inv(A).dot(B);
print(X)

[-2.33333333  3.33333333]


In [7]:
price = -2.33*92.21+3.33*75.84;
print(price)

37.697900000000004


### 4.11 Running PV


In [44]:
#calculate d(0,k)
cashflow = np.array([-40,10,10,10,10,10,10]);
s = np.array([5.0,5.3,5.6,5.8,6.0,6.1]);
d0 = np.zeros(shape=(6,1));
for i in range (0,6):
    d0[i]= 1/((1+s[i]/100)**(i+1));   
print(d0)

[[0.95238095]
 [0.90186858]
 [0.8491966 ]
 [0.79810003]
 [0.74725817]
 [0.70098334]]


In [30]:
#calculate net value base on d(0,k)
pv = np.zeros(shape=(7,1));
for i in range (0,6):
    pv[i] = d0[i]*cashflow[i+1];
npv = np.sum(pv)-40;
print(npv)

9.497876784246984


In [45]:
#calculate f(i,j)
d = np.zeros(shape=(6,1));
f = np.zeros(shape=(6,1));
for i in range (0,5):
    f[i] = ((1+s[i+1]/100)**(i+2)/(1+s[i]/100)**(i+1))-1;
print(f)

[[0.05600857]
 [0.06202567]
 [0.06402276]
 [0.06803788]
 [0.06601417]
 [0.        ]]


In [46]:
#calculate d(i,j)
for i in range(0,5):
    d[i] = 1/(1+f[i]);
print(d)

[[0.94696201]
 [0.94159683]
 [0.93982952]
 [0.93629638]
 [0.93807384]
 [0.        ]]


### 4.15 Immunization

Given yield, calculate normal duration 

In [7]:

F1= 100; #face value
y1 = 0.09; #yield to maturity
m1 = 2; #number of coupon payments per year
n1 = 10; #number of coupon periods
c1 = 0.08; #yearly coupy payment, how many percent bond

P1 = F1/((1+y1/m1)**n1)+(c1/y1)*(1-(1/(1+y1/m1)**n1));
D1 = ((1+y1/m1)/(m1*y1/m1))-(1+y1/m1+n1*m1*(c1/m1-y1/m1))/(m1*(c1/m1)*((1+y1/m1)**(n1*m1)-1)+m1*y1/m1);
print(P1)
print(D1)

64.7092769300887
6.954496339267785


Calculate price and quasi-modified (if given spot rates) duration for bond 2

In [2]:
import numpy as np
s = np.array([0.0767, 0.0827, 0.0881, 0.0931, 0.0975, 0.1016, 0.1052, 0.1085, 0.1115, 0.1142, 0.1167, 0.1189]);
b1 = np.array([6,6,6,6,6,6,6,6,6,6,6,106]);
PV1 = np.zeros(shape=(12,1));
for i in range(0,12):
    PV1[i] = b1[i]/(1+s[i])**(i+1);
P1 = np.sum(PV1)
print(P1)
minusPV1prime = np.zeros(shape=(12,1));
for i in range(0,12):
    minusPV1prime[i] = (b1[i]*(i+1))/(1+s[i])**(i+2);
minusdP1dLambda = np.sum(minusPV1prime);
D1 = minusdP1dLambda/P1;
print(D1)

65.95141593517083
7.065794607835234


Calculate price and quasi-modified duration for bond 2

In [3]:
s = np.array([0.0767, 0.0827, 0.0881, 0.0931, 0.0975, 0.1016, 0.1052, 0.1085, 0.1115, 0.1142, 0.1167, 0.1189]);
b2 = np.array([10,10,10,10,110]);
PV2 = np.zeros(shape=(5,1));
for i in range(0,5):
    PV2[i] = b2[i]/(1+s[i])**(i+1);
P2 = np.sum(PV2)
print(P2)
minusPV2prime = np.zeros(shape=(5,1));
for i in range(0,5):
    minusPV2prime[i] = (b2[i]*(i+1))/(1+s[i])**(i+2);
minusdP2dLambda = np.sum(minusPV2prime);
D2 = minusdP2dLambda/P2;
print(D2)

101.66772356861858
3.7981038674959344


Calculate Price and Duration for obligation

In [4]:
ob = np.array([500,900,600,500,100,100,100,50]);
PVob = np.zeros(shape=(8,1));
for i in range (0,8):
    PVob[i] = ob[i]/(1+s[i])**(i+1);
Pob = np.sum(PVob);
print(Pob);
minusPVobprime = np.zeros(shape=(8,1));
for i in range(0,8):
    minusPVobprime[i] = (ob[i]*(i+1))/(1+s[i])**(i+2);
minusdPobdLambda = np.sum(minusPVobprime);
Dob = minusdPobdLambda/Pob;
print(Dob)

2238.437650905573
2.4476042424124693


In [5]:
A = np.array([[P1, P2], [P1*D1, P2*D2]]);
B = np.array([Pob, Pob*Dob]);
X = np.linalg.inv(A).dot(B);
print(X)

[-14.02731012  31.1166465 ]
