In [29]:
import numpy as np
index = np.array([12.3, 5.5, 4.3, 6.7, 9.7, 8.3, 5.6, 5.7, 5.7, 3.6]);
stock_1 = np.array([11.91, 18.37, 3.64, 24.37, 30.42, -1.45, 20.11, 9.28, 17.63, 15.71]);
stock_2 = np.array([29.59, 15.25, 3.53, 17.67, 12.74, -2.56, 25.46, 6.92, 9.73, 25.09]);
stock_3 = np.array([23.27, 19.47, -6.58, 15.08, 16.24, -15.05, 17.80, 18.82, 3.05, 16.94]);
stock_4 = np.array([27.24, 17.05, 10.20, 20.26, 19.84, 1.51, 12.24, 16.12, 22.93, 3.49]);
market = (stock_1+stock_2+stock_3+stock_4)/4
riskless = np.array([6.2, 6.7, 6.4, 5.7, 5.9, 5.2, 4.9, 5.5, 6.1, 5.8])

In [30]:
rf = np.mean(riskless)
mu_market = np.mean(market)
mu_index = np.mean(index)
mu_stock1 = np.mean(stock_1)
mu_stock2 = np.mean(stock_2)
mu_stock3 = np.mean(stock_3)
mu_stock4 = np.mean(stock_4)

In [36]:
from statistics import variance
var_market = variance(market)
var_index = variance(index)
var_stock1 = variance(stock_1)
var_stock2 = variance(stock_2)
var_stock3 = variance(stock_3)
var_stock4 = variance(stock_4)

### Example 8.1

In [1]:
B1 = np.cov(stock_1,index);
b1 = B1[1,0]/var_index
a1 = mu_stock1 - b1*mu_index
e_stock1 = stock_1 - a1 - b1*index
e_var1 = var_stock1 - (b1**2)*var_index
print(B1)

NameError: name 'np' is not defined

In [85]:
B2 = np.cov(stock_2,index);
b2 = B2[1,0]/var_index
a2 = mu_stock2 - b2*mu_index
e_stock2 = stock_2 - a2 - b2*index
e_var2 = var_stock2 - (b2**2)*var_index
print(e_var2)

103.66829953135705


In [86]:
B3 = np.cov(stock_3,index);
b3 = B3[1,0]/var_index
a3 = mu_stock3 - b3*mu_index
e_stock3 = stock_3 - a3 - b3*index
e_var3 = var_stock3 - (b3**2)*var_index
print(e_var3)

157.955680732312


In [87]:
B4 = np.cov(stock_4,index);
b4 = B4[1,0]/var_index
a4 = mu_stock4 - b4*mu_index
e_stock4 = stock_4 - a4 - b4*index
e_var4 = var_stock4 - (b4**2)*var_index
print(e_var4)

50.53606237471659


In [88]:
print(np.cov(e_stock1, e_stock2))

[[ 89.47668399  49.22072378]
 [ 49.22072378 103.66829953]]


In [89]:
print(np.cov(e_stock2, e_stock3))

[[103.66829953 101.49105759]
 [101.49105759 157.95568073]]


In [90]:
print(np.cov(e_stock3, e_stock4))

[[157.95568073  47.85989734]
 [ 47.85989734  50.53606237]]


### Example 8.2


In [97]:
B1 = np.cov(stock_1,market);
beta1 = B1[1,0]/var_market
alpha1 = (mu_stock1-rf)- beta1*(mu_market-rf)
e_stock1 = stock_1 - alpha1 - beta1*market
e_var1 = var_stock1 - (beta1**2)*var_market
print(e_var1)

31.51934572254129


In [99]:
B2 = np.cov(stock_2,market);
beta2 = B2[1,0]/var_market
alpha2 = (mu_stock2-rf)- beta2*(mu_market-rf)
e_stock2 = stock_2 - alpha2 - beta2*market
e_var2 = var_stock2 - (beta2**2)*var_market
print(e_var2)

32.07369510932082


In [100]:
B3 = np.cov(stock_3,market);
beta3 = B3[1,0]/var_market
alpha3 = (mu_stock3-rf)- beta3*(mu_market-rf)
e_stock3 = stock_3 - alpha3 - beta3*market
e_var3 = var_stock3 - (beta3**2)*var_market
print(e_var3)

21.36208948208815


In [102]:
B4 = np.cov(stock_4,market);
beta4 = B4[1,0]/var_market
alpha4 = (mu_stock4-rf)- beta4*(mu_market-rf)
e_stock4 = stock_4 - alpha4 - beta4*market
e_var4 = var_stock4 - (beta4**2)*var_market
print(e_var4)

34.97841245813016


### Exercise 8.3

In [74]:
import numpy as np
index = np.array([12.3, 5.5, 4.3, 6.7, 9.7, 8.3, 5.6, 5.7, 5.7, 3.6]);
stock_1 = np.array([11.91, 18.37, 3.64, 24.37, 30.42, -1.45, 20.11, 9.28, 17.63, 15.71]);
stock_2 = np.array([29.59, 15.25, 3.53, 17.67, 12.74, -2.56, 25.46, 6.92, 9.73, 25.09]);
stock_3 = np.array([23.27, 19.47, -6.58, 15.08, 16.24, -15.05, 17.80, 18.82, 3.05, 16.94]);
stock_4 = np.array([27.24, 17.05, 10.20, 20.26, 19.84, 1.51, 12.24, 16.12, 22.93, 3.49]);
market = (stock_1+stock_2+stock_3+stock_4)/4
riskless = np.array([6.2, 6.7, 6.4, 5.7, 5.9, 5.2, 4.9, 5.5, 6.1, 5.8])

In [97]:
R = np.stack((stock_1,stock_2,stock_3,stock_4), axis = 0)
V = np.cov(R)
print(V)

[[ 90.26465444  50.89496889  79.02409333  40.17989778]
 [ 50.89496889 107.22566222 105.37893556  30.98590444]
 [ 79.02409333 105.37893556 162.20478222  56.53679778]
 [ 40.17989778  30.98590444  56.53679778  68.25477333]]


In [98]:
w,v = eig(V)
#w is egigenvalue and v is eigenvector
print(v)
print(w)

[[ 0.41850798  0.51318117  0.73665617  0.13723645]
 [ 0.5073799  -0.54934435 -0.02912528  0.66327832]
 [ 0.69300114 -0.17820203 -0.14214733 -0.68395   ]
 [ 0.29523911  0.63490937 -0.66051763  0.27099894]]
[311.16736846  58.05278743  36.97666605  21.75305028]


In [130]:
P = np.zeros(shape = (4,1))
for i in range (0,4):
    P[i] = v[i,0] / (np.sum(v[:,0]))
PC = np.matmul(np.transpose(R),P)

In [127]:
print(np.transpose(PC))

[[23.07382172 17.73762871  0.92256705 18.59668812 18.96786036 -6.21148867
  19.4779201  13.16336061 11.07480113 16.75684371]]


In [129]:
print(market)

[23.0025 17.535   2.6975 19.345  19.81   -4.3875 18.9025 12.785  13.335
 15.3075]


### Exercise 8.5

In [180]:
from statistics import variance
from numpy.linalg import multi_dot
r = np.array([0.02, 0.34, 0.12, 0.34, 0.67, 0.11, 0.33, 0.56, 0.34, -0.28]);
F = np.array([0.4, 0.8, 0.14, 0.66, 0.9, 0.2, 0.18, 0.47, 0.21, -0.3]);
ones = np.array([1,1,1,1,1,1,1,1,1,1])

In [181]:
A = np.stack((ones,F), axis =1)
print(A)

[[ 1.    0.4 ]
 [ 1.    0.8 ]
 [ 1.    0.14]
 [ 1.    0.66]
 [ 1.    0.9 ]
 [ 1.    0.2 ]
 [ 1.    0.18]
 [ 1.    0.47]
 [ 1.    0.21]
 [ 1.   -0.3 ]]


In [182]:
A1 = np.matmul(np.transpose(A),A)
x = multi_dot([np.linalg.inv(A1),np.transpose(A),np.reshape(r,(10,1))])
print(x)

[[0.0356933 ]
 [0.59919864]]
