In [29]:
import numpy as np
index = np.array([12.3, 5.5, 4.3, 6.7, 9.7, 8.3, 5.6, 5.7, 5.7, 3.6]);
stock_1 = np.array([11.91, 18.37, 3.64, 24.37, 30.42, -1.45, 20.11, 9.28, 17.63, 15.71]);
stock_2 = np.array([29.59, 15.25, 3.53, 17.67, 12.74, -2.56, 25.46, 6.92, 9.73, 25.09]);
stock_3 = np.array([23.27, 19.47, -6.58, 15.08, 16.24, -15.05, 17.80, 18.82, 3.05, 16.94]);
stock_4 = np.array([27.24, 17.05, 10.20, 20.26, 19.84, 1.51, 12.24, 16.12, 22.93, 3.49]);
market = (stock_1+stock_2+stock_3+stock_4)/4
riskless = np.array([6.2, 6.7, 6.4, 5.7, 5.9, 5.2, 4.9, 5.5, 6.1, 5.8])

In [30]:
rf = np.mean(riskless)
mu_market = np.mean(market)
mu_index = np.mean(index)
mu_stock1 = np.mean(stock_1)
mu_stock2 = np.mean(stock_2)
mu_stock3 = np.mean(stock_3)
mu_stock4 = np.mean(stock_4)

In [36]:
from statistics import variance
var_market = variance(market)
var_index = variance(index)
var_stock1 = variance(stock_1)
var_stock2 = variance(stock_2)
var_stock3 = variance(stock_3)
var_stock4 = variance(stock_4)

### Example 8.1

In [84]:
B1 = np.cov(stock_1,index);
b1 = B1[1,0]/var_index
a1 = mu_stock1 - b1*mu_index
e_stock1 = stock_1 - a1 - b1*index
e_var1 = var_stock1 - (b1**2)*var_index
print(e_var1)

89.47668399091675


In [85]:
B2 = np.cov(stock_2,index);
b2 = B2[1,0]/var_index
a2 = mu_stock2 - b2*mu_index
e_stock2 = stock_2 - a2 - b2*index
e_var2 = var_stock2 - (b2**2)*var_index
print(e_var2)

103.66829953135705


In [86]:
B3 = np.cov(stock_3,index);
b3 = B3[1,0]/var_index
a3 = mu_stock3 - b3*mu_index
e_stock3 = stock_3 - a3 - b3*index
e_var3 = var_stock3 - (b3**2)*var_index
print(e_var3)

157.955680732312


In [87]:
B4 = np.cov(stock_4,index);
b4 = B4[1,0]/var_index
a4 = mu_stock4 - b4*mu_index
e_stock4 = stock_4 - a4 - b4*index
e_var4 = var_stock4 - (b4**2)*var_index
print(e_var4)

50.53606237471659


In [88]:
print(np.cov(e_stock1, e_stock2))

[[ 89.47668399  49.22072378]
 [ 49.22072378 103.66829953]]


In [89]:
print(np.cov(e_stock2, e_stock3))

[[103.66829953 101.49105759]
 [101.49105759 157.95568073]]


In [90]:
print(np.cov(e_stock3, e_stock4))

[[157.95568073  47.85989734]
 [ 47.85989734  50.53606237]]


### Example 8.2


In [97]:
B1 = np.cov(stock_1,market);
beta1 = B1[1,0]/var_market
alpha1 = (mu_stock1-rf)- beta1*(mu_market-rf)
e_stock1 = stock_1 - alpha1 - beta1*market
e_var1 = var_stock1 - (beta1**2)*var_market
print(e_var1)

31.51934572254129


In [99]:
B2 = np.cov(stock_2,market);
beta2 = B2[1,0]/var_market
alpha2 = (mu_stock2-rf)- beta2*(mu_market-rf)
e_stock2 = stock_2 - alpha2 - beta2*market
e_var2 = var_stock2 - (beta2**2)*var_market
print(e_var2)

32.07369510932082


In [100]:
B3 = np.cov(stock_3,market);
beta3 = B3[1,0]/var_market
alpha3 = (mu_stock3-rf)- beta3*(mu_market-rf)
e_stock3 = stock_3 - alpha3 - beta3*market
e_var3 = var_stock3 - (beta3**2)*var_market
print(e_var3)

21.36208948208815


In [102]:
B4 = np.cov(stock_4,market);
beta4 = B4[1,0]/var_market
alpha4 = (mu_stock4-rf)- beta4*(mu_market-rf)
e_stock4 = stock_4 - alpha4 - beta4*market
e_var4 = var_stock4 - (beta4**2)*var_market
print(e_var4)

34.97841245813016
