Consider the following table of annual rates of return, in percentage, for four common risky assets over the time period 2010 to 2019

Berkshire Hathaway (ticker:  BRK/A)
S&P 500 Index (ticker: SPX) 
NASDAQ 100 Index (ticker: NDX)
Russell 2000 Index (ticker:  RUT)

Assuming there is no risk-free asset available, suppose you desire to invest in a portfolio of these 4 risky assets such that you minimize the portfolio variance, subject to the constraint that the portfolio weights sum to 1. Note that short positions (negative weights) are permissible.  

Using mean-variance portfolio optimization, determine the 4 minimum variance portfolio weightings and the minimum portfolio variance.

Please enter your solutions in the answer boxes for Questions 1 to 5.

What is the portfolio weight for BRK/A?

Please express your numerical answer in decimal (not percentage) form and round your answer to two decimal places.



In [1]:
import numpy as np
brka = np.array([0.214, -0.047, 0.168, 0.327, 0.27, -0.125, 0.234, 0.219, 0.028, 0.11]);
spx = np.array([0.151, 0.021, 0.16, 0.324, 0.137, 0.014, 0.12, 0.218, -0.044, 0.315]);
ndx = np.array([0.1922, 0.027, 0.1682, 0.3499, 0.1794, 0.0843, 0.0589, 0.3152, -0.0104,0.3796]);
rut = np.array([0.2685, -0.0418, 0.1635, 0.3882, 0.0489, -0.0441, 0.2131, 0.1465, -0.1101, 0.2552]);

In [2]:
R = np.stack((brka, spx, ndx, rut), axis = 0)
V = np.cov(R)
print(V)

[[0.02131596 0.01229758 0.0112067  0.01771535]
 [0.01229758 0.01504027 0.01604968 0.01756213]
 [0.0112067  0.01604968 0.0189387  0.01677366]
 [0.01771535 0.01756213 0.01677366 0.02598459]]


In [24]:
B = np.ones(shape=(4,1))
v = np.linalg.inv(V).dot(B)
w = np.zeros(shape=(4,1));
for i in range (0,4):
    w[i] = v[i]/np.sum(v);
print(w)

[[ 0.25521027]
 [ 2.73456349]
 [-1.10150645]
 [-0.88826731]]


In [25]:
print(np.transpose(w).dot(V).dot(w))

[[109.8834123]]


Again consider the table of annual rates of return, in percentage, for four common risky assets over the time period 2010 to 2019 presented in Question 1.

Now assume there is a risk-free asset available and the annual risk-free rate is 2%.   Using mean-variance portfolio theory, determine the 4 portfolio weightings and the portfolio variance for the unique fund F defined by the tangent portfolio and the one-fund theorem.

Note that the portfolio weights sum to 1 and short selling (negative weights) are permissible.  

Please enter your solutions in the answer boxes for Questions 6 to 10.

What is the portfolio weight for BRK/A in the unique fund F?

Please express your numerical answer in decimal (not percentage) form and round your answer to two decimal places.

In [12]:
rf = 0.02;
r_bar = np.array([[np.mean(brka)-rf],
                [np.mean(spx)-rf],
                [np.mean(ndx)-rf],
                 [np.mean(rut)-rf]]);
v1 = np.linalg.inv(V).dot(r_bar)
w1 = np.zeros(shape=(4,1));
for i in range (0,4):
    w1[i] = v1[i]/np.sum(v1);
print(w1)

[[ 0.63764966]
 [-0.90053972]
 [ 1.725156  ]
 [-0.46226594]]


In [13]:
print(np.transpose(w1).dot(V).dot(w1))

[[0.02087017]]


In [15]:
import numpy as np
brka = np.array([21.4, -4.7, 16.8, 32.7, 27, -12.5, 23.4, 21.9, 2.8, 11]);
spx = np.array([15.1, 2.1, 16, 32.4, 13.7, 1.4, 12, 21.8, -4.4, 31.5]);
ndx = np.array([19.22, 2.7, 16.82, 34.99, 17.94, 8.43, 5.89, 31.52, -1.04,37.96]);
rut = np.array([26.85, -4.18, 16.35, 38.82, 4.89, -4.41, 21.31, 14.65, -11.01, 25.52]);

In [16]:
R = np.stack((brka, spx, ndx, rut), axis = 0)
V = np.cov(R)
B = np.ones(shape=(4,1))
v = np.linalg.inv(V).dot(B)
w = np.zeros(shape=(4,1));
for i in range (0,4):
    w[i] = v[i]/np.sum(v);
print(w)

[[ 0.25521027]
 [ 2.73456349]
 [-1.10150645]
 [-0.88826731]]


In [26]:
print((np.transpose(w).dot(V).dot(w))/10000)

[[0.01098834]]


In [27]:
print(r_bar)

[[0.1198 ]
 [0.1216 ]
 [0.15443]
 [0.10879]]


In [28]:
print(np.mean(rut))

12.879
